//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altered.Logs.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Altered.Logs.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;version&quot;: &quot;0&quot;,
        ///    &quot;id&quot;: &quot;5a2570eb-9e41-6f9c-e2c7-cd0afe271ce9&quot;,
        ///    &quot;detail-type&quot;: &quot;CodePipeline Action Execution State Change&quot;,
        ///    &quot;source&quot;: &quot;aws.codepipeline&quot;,
        ///    &quot;account&quot;: &quot;002067833750&quot;,
        ///    &quot;time&quot;: &quot;2019-03-28T19:25:23Z&quot;,
        ///    &quot;region&quot;: &quot;us-east-1&quot;,
        ///    &quot;resources&quot;: [
        ///        &quot;arn:aws:codepipeline:us-east-1:002067833750:pipeline-example.pipeline&quot;
        ///    ],
        ///    &quot;detail&quot;: {
        ///        &quot;pipeline&quot;: &quot;pipeline-example.pipeline&quot;,
        ///        &quot;execution-id&quot;: &quot;78d7c4d7-05b5-4560-a494-98f1dc4b1c5b&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CodePipelineEvent {
            get {
                return ResourceManager.GetString("CodePipelineEvent", resourceCulture);
            }
        }
    }
}
